using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;

namespace e_Portfolio_System
{
    public class Parent
    {
        public int parentId { get; set; }
        public string name { get; set; }
        public string emailAddr { get; set; }
        public string password { get; set; }

        public int add()
        {
            //Read connection string "NPBookConnectionString" from web.config file.
            string strConn = ConfigurationManager.ConnectionStrings
                                ["Student_EPortfolio"].ToString();

            //Instantiate a SqlConnection object with the Connection String read.
            SqlConnection conn = new SqlConnection(strConn);

            // Instantiate a SqlCommand object, supply it with an INSERT SQL statement 
            // which will return the auto-generated StaffID after insertion,
            // and the connection object for connecting to the database.

            SqlCommand cmd = new SqlCommand(
                "INSERT INTO Parent (parentName, emailAddr, password) OUTPUT INSERTED.ParentID VALUES(@name, @emailAddr, @password)", conn);

            //Define parameters
            cmd.Parameters.AddWithValue("@name", name);
            cmd.Parameters.AddWithValue("@emailAddr", emailAddr);
            cmd.Parameters.AddWithValue("@password", password);

            //Connection to database must be opened before any ops are made
            conn.Open();

            //ExecuteScalar used to retrieve the autogenerated staff ID after executing the insert sql statemen
            int id = (int)cmd.ExecuteScalar();

            //Connection should be closed after operations
            conn.Close();

            //No error
            return id;
        }

        public bool isEmailExist(string emailAddr)
        {
            string strConn = ConfigurationManager.ConnectionStrings
                                ["Student_EPortfolio"].ToString();

            SqlConnection conn = new SqlConnection(strConn);
            SqlCommand cmd = new SqlCommand
                             ("SELECT * FROM Parent WHERE EmailAddr = @selectedEmail", conn);

            cmd.Parameters.AddWithValue("@selectedEmail", emailAddr);

            SqlDataAdapter daEmail = new SqlDataAdapter(cmd);
            DataSet result = new DataSet();

            conn.Open();
            // Use DataAdapter to fetch data to a table "EmailDetails" in DataSet.
            daEmail.Fill(result, "EmailDetails");
            conn.Close();

            if (result.Tables["EmailDetails"].Rows.Count > 0)
                return true; // The email given exists
            else
                return false; // The email given does not exist
        }

        




        //public int update()
        //{
        //    // Read connection string "Student_EPortfolio" from web.config file.
        //    string strConn = ConfigurationManager.ConnectionStrings
        //                        ["Student_EPortfolio"].ToString();

        //    // Instantiate a SqlConnection object with the Connection String read.
        //    SqlConnection conn = new SqlConnection(strConn);

        //    // Instantiate a SqlCommand object, supply it with an SQL statement 
        //    // and the connection object for connecting to the database.
        //    SqlCommand cmd = new SqlCommand
        //        ("UPDATE Parent SET Password = @password, Email = @emailAddr " +
        //        "WHERE ParentID = @selectedParentID", conn);

        //    //Define the parameters used in SQL statement, value for each parameter
        //    //is retrieved from respective class's property
        //    cmd.Parameters.AddWithValue("@password", password);
        //    cmd.Parameters.AddWithValue("@emailAddr", emailAddr);
        //    cmd.Parameters.AddWithValue("@selectedParentID", parentId);

        //    // Open a database connection
        //    conn.Open();

        //    // ExecuteNonQuery is used for UPDATE and DELETE
        //    int count = cmd.ExecuteNonQuery();

        //    // Close database connection
        //    conn.Close();

        //    // Check if update successful
        //    if (count > 0) // at least 1 row updated
        //        return 0; // update successful
        //    else
        //        return -2; // no update done
        //}





        //public int GetParentDetails()
        //{
        //    // Read connection string "Student_EPortfolio" from web.config file.
        //    string strConn = ConfigurationManager.ConnectionStrings
        //                        ["Student_EPortfolio"].ToString();

        //    // Instantiate a SqlConnection object with the Connection String read.
        //    SqlConnection conn = new SqlConnection(strConn);

        //    // Instantiate a SqlCommand object, supply it with a SELECT SQL
        //    // statement which retrieves all attributes of a student record.
        //    SqlCommand cmd = new SqlCommand("Select * From Student" +
        //        " full Join ViewingRequest on Student.Name = ViewingRequest.StudentName" +
        //        " right join Parent on Parent.ParentID = ViewingRequest.ParentID" 
        //        //+
        //        //"WHERE (ParentID = @currentParentId AND ViewingRequest.Status = 'A') " +
        //        //"OR (ParentID = @currentParentId AND ViewingRequest.Status = 'P') "
        //        , conn);


        //    // Define the parameter used in SQL statement, value for the 
        //    // parameter is retrieved from the studentId property of the Student class.
        //    cmd.Parameters.AddWithValue("@currentParentId", parentId);


        //    // Instantiate a DataAdapter object, pass the SqlCommand
        //    // object created as parameter.
        //    SqlDataAdapter daParent = new SqlDataAdapter(cmd);

        //    // Created a DataSet object result
        //    DataSet result = new DataSet();

        //    // Open a database connection
        //    conn.Open();

        //    // Use DataAdapter to fetch data to a table "StudentDetails" in DataSet.
        //    daParent.Fill(result, "ParentDetails");



        //    // Close database connection
        //    conn.Close();

        //    if (result.Tables["ParentDetails"].Rows.Count > 0)
        //    {
        //        // Fill Student object with values from the DataSet
        //        DataTable table = result.Tables["ParentDetails"];
        //        if (!DBNull.Value.Equals(table.Rows[0]["parentname"]))
        //            name = table.Rows[0]["parentname"].ToString();
        //        if (!DBNull.Value.Equals(table.Rows[0]["emailAddr"]))
        //            emailAddr = table.Rows[0]["emailAddr"].ToString();
        //        if (!DBNull.Value.Equals(table.Rows[0]["password"]))
        //            password = table.Rows[0]["password"].ToString();

        //        return 0; // No error occurs
        //    }

        //    else
        //    {
        //        return -1;
        //    }
        //}


    }

}